### ISSUE TITLE
Traceback in student output when Python code has NameError (or others presumably)

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#124]
<img width="529" alt="screen shot 2018-08-13 at 12 28 07 pm" src="https://user-images.githubusercontent.com/788678/44044711-79bea27a-9ef4-11e8-92ce-decda7145893.png">

# `__init__.py`

```
import check50

@check50.check()
def exists():
    """mario.py exists."""
    check50.exists("mario.py")

@check50.check(exists)
def compiles():
    """no syntax errors in mario.py."""
    check50.run("python -m py_compile mario.py").exit(0)

@check50.check(compiles)
def prints_four_question_marks():
    """prints four question marks"""
    check50.run("python mario.py").stdout("\?\?\?\?", "????").exit(0)
```

# `.cs50.yaml`

```
lab50:
  file:
    - mario.py

submit50:
  files: &files
    - !exclude "*"
    - !require mario.py

check50:
  files: *files
```
